version: '3.8'

services:
  app:
    networks:
    - localnet
    image: nostrcheckme/nostrcheck-server:app
    build: .
    depends_on:
        redis:
          condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - ./tmp:/usr/src/app/tmp
      - media:/usr/src/app/media
      - ./resources:/usr/src/app/resources
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.app.loadbalancer.server.port=3000"
      - "traefik.http.services.app.loadbalancer.sticky.cookie=true"
      - "traefik.http.services.app.loadbalancer.sticky.cookie.name=app_session"
      - "traefik.http.routers.app.entrypoints=web"
      # ... (resto de tus etiquetas)
    environment:
      - WAIT_HOSTS=redis:6379
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    command: sh -c "/wait && npm run start"
  # ... (resto de tus servicios)